### ISSUE TITLE
Module has no exported member 'OpaqueToken'

### ISSUE THREAD

**Issue by germwire** [SteveDunlap13/MaterialTimeControl#13]
ERROR in node_modules/material-time-control/node_modules/@angular/flex-layout/media-query/breakpoints/break-points.d.ts(8,10)
Module  has no exported member 'OpaqueToken'
"@angular/animations": "^5.2.1",
    "@angular/cdk": "^5.1.0",
    "@angular/cli": "^1.6.5",
    "@angular/common": "^5.2.1",
    "@angular/compiler": "^5.2.1",
    "@angular/core": "^5.2.1",
    "@angular/flex-layout": "^5.0.0-beta.13",
    "@angular/forms": "^5.2.1",
    "@angular/http": "^5.2.1",
    "@angular/material": "^5.1.0",
    "@angular/platform-browser": "^5.2.1",
    "@angular/platform-browser-dynamic": "^5.2.1",
    "@angular/router": "^5.2.1",

**Comment by amalga** [comment]
Did you find a solution for this error?

**Comment by joshorvis** [comment]
Same problem here, watching

**Comment by SteveDunlap13** [comment]
Apologies, that I haven't responded to this before.  I put this control up on Git for demo purposes.  It was not meant for production or product inclusion; only for reference how to build the control and use it in your own implementation.  With Angular always being updated, the state of this control with the current release may not work.  But, please by all means use the code to build / implement your own time control.
