### ISSUE TITLE
Trouble using time control

### ISSUE THREAD

**Issue by madmandrew** [SteveDunlap13/MaterialTimeControl#14]
First I had to install GIT to get it to run npm install. So that's not ideal.  Second I'm getting error

`The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository
 to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (C:\dev\projects\BackOfficeServices-ui\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:662:23)
    at plugin.done.then (C:\dev\projects\BackOfficeServices-ui\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/app.module.ts 25:37-102
 @ ./src/main.ts
 @ multi ./src/main.ts
`

I'm importing into my modules like so.
`import {MaterialTimeControlModule} from 'material-time-control/src/material-time-control.module'`

**Comment by SteveDunlap13** [comment]
Apologies, that I haven't responded to this before.  I put this control up on Git for demo purposes.  It was not meant for production or product inclusion; only for reference how to build the control and use it in your own implementation.  Thanks.
