### ISSUE TITLE
Getting time value

### ISSUE THREAD

**Issue by maartri** [SteveDunlap13/MaterialTimeControl#16]
Hi Steve. Its seems I can't get the value of your timepicker in typescript using ngModel. 

Or am I doing it wrong?

**Comment by Antebios** [comment]
I'm using https://github.com/sssiegmeister/MaterialTimeControl fork of this project.  I was able to get the time value using the "userTimeChange" event within the "mate-datepicker-toggle" like this:

`<mat-form-field>


              <input matInput [matTimepicker]="startTimePicker" placeholder="Start Time">
              <mat-timepicker-toggle matSuffix [for]="startTimePicker"  (userTimeChange)="onChangeStartTime(startTimePicker.userTime)"></mat-timepicker-toggle>
              <mat-timepicker #startTimePicker color="primary" disabled="false"></mat-timepicker>
            </mat-form-field>`

**Comment by SteveDunlap13** [comment]
Apologies, that I haven't responded to this before.  I put this control up on Git for demo purposes.  It was not meant for production or product inclusion; only for reference how to build the control and use it in your own implementation.  Thanks.
