### ISSUE TITLE
Documentation for MaterialTimeControl

### ISSUE THREAD

**Issue by AlexKovalov** [SteveDunlap13/MaterialTimeControl#18]
Hello Steve. I`d like to use your MaterialTimeControl, where could I find the documentation for it.
Thanks for advance.

**Comment by SteveDunlap13** [comment]
Apologies.  I put this control up on Git for demo purposes.  It was not meant for production or product inclusion; only for reference how to build the control and use it in your own implementation.  Please feel free to use this code to build / implement your own time control.  Thanks.
