### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by leocaseiro** [SteveDunlap13/MaterialTimeControl#2]
Hi @SteveDunlap13, thanks for this lib. I was wondering if you are planning to publish on npm.

I couldn't find to download from there.
Thanks

**Comment by SteveDunlap13** [comment]
Sorry, there isn't an npm package for this.  Dig down and look at the time-control folder at https://github.com/SteveDunlap13/MaterialTimeControl/tree/master/src/app/ui/time-control to see the components.
Everyone implements angular/material/flex/etc. differently and the component(s) probably need a bit of tweaking for your use.

**Comment by SteveDunlap13** [comment]
Closed as per my previous comment.

**Comment by leocaseiro** [comment]
np thanks!
