### ISSUE TITLE
24 hours functionality

### ISSUE THREAD

**Issue by Francis-Ide** [SteveDunlap13/MaterialTimeControl#4]
Is it possible to integrate the 24 hours functionality ?
I've read your remark that this could be done easily, but I'm not quite familiar with the CSS stuff that is being used here.

Thx

**Comment by SteveDunlap13** [comment]
Sure.  I'll try and update the control accordingly over the holidays.

**Comment by 3799605037** [comment]
Eager to see this implemented. Thank you for your work @SteveDunlap13!

**Comment by SemVC7** [comment]
Hi Steve! I adore your material time control & look forward to see your 24 hours functionality implementation.

**Comment by SteveDunlap13** [comment]
All done; merged to master.
